version: '3'
services:
  db:
    image: postgres:11.8
    container_name: 'recruit_postgres'
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGDATA : /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    stop_signal: SIGINT
  postgrest:
    image: postgrest/postgrest
    container_name: 'recruit_api'
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/database
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  adminer:
    image: adminer:latest
    container_name: 'adminer'
    restart: always
    environment:
      ADMINER_DESIGN: 'pappu687'
    ports:
      - "8082:8080"
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
        - postgrest:postgrest
    environment:
      API_URL: http://localhost:3000
